
spring:
  datasource:
    url: jdbc:mysql://rm-bp13vp0z97x63ra08po.mysql.rds.aliyuncs.com:3306/zevindb?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8&allowMultiQueries=true
    username: zevindb
    password: 6212601Fang
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: zevin.club
    port: 6379
    password: password
server:
  port: 8088

